# HOW TO USE NUMPY?
## Part - 6

In [28]:
import numpy as np

In [29]:
ar = np.random.randint(1,100,(20,5))

In [30]:
print(ar)

[[ 9 11 40 59 73]
 [33 75 61 60 42]
 [74 77 43 54 91]
 [93 48 18 91 70]
 [51 48 80 68 55]
 [24 57 57 92 74]
 [25 48 77  8 32]
 [38 63 16 40 86]
 [86  8 10 95  3]
 [90 64  6 84 81]
 [74 48 50 66 76]
 [93 40 58 33 32]
 [50 28 12 76  2]
 [26 61  6 67 85]
 [82 31 29 30 10]
 [74 17 58 65 28]
 [46 21  3  9 51]
 [61 15 41 24 38]
 [53 84 62 98 31]
 [17 91 50 44 88]]


**Extract** a part of array

In [31]:
print(ar[0:3])

[[ 9 11 40 59 73]
 [33 75 61 60 42]
 [74 77 43 54 91]]


In [32]:
print(ar[:,0:3])

[[ 9 11 40]
 [33 75 61]
 [74 77 43]
 [93 48 18]
 [51 48 80]
 [24 57 57]
 [25 48 77]
 [38 63 16]
 [86  8 10]
 [90 64  6]
 [74 48 50]
 [93 40 58]
 [50 28 12]
 [26 61  6]
 [82 31 29]
 [74 17 58]
 [46 21  3]
 [61 15 41]
 [53 84 62]
 [17 91 50]]


In [33]:
print(ar[0:5,0:3])

[[ 9 11 40]
 [33 75 61]
 [74 77 43]
 [93 48 18]
 [51 48 80]]


In [34]:
B = ar[0:2,2:5]

In [35]:
print(B)

[[40 59 73]
 [61 60 42]]


In fact, the alias variable **B** is part of the entire array **ar** and by changing its values, changes in **ar** are also taken into account.

In [36]:
B[:] = 100

In [37]:
print(ar)

[[  9  11 100 100 100]
 [ 33  75 100 100 100]
 [ 74  77  43  54  91]
 [ 93  48  18  91  70]
 [ 51  48  80  68  55]
 [ 24  57  57  92  74]
 [ 25  48  77   8  32]
 [ 38  63  16  40  86]
 [ 86   8  10  95   3]
 [ 90  64   6  84  81]
 [ 74  48  50  66  76]
 [ 93  40  58  33  32]
 [ 50  28  12  76   2]
 [ 26  61   6  67  85]
 [ 82  31  29  30  10]
 [ 74  17  58  65  28]
 [ 46  21   3   9  51]
 [ 61  15  41  24  38]
 [ 53  84  62  98  31]
 [ 17  91  50  44  88]]


To solve the problem, The **ar** array should be a copy to **B**

In [38]:
B = ar.copy()

Conditional orders can be applied directly to arrays, the output is an array of true and false.

In [40]:
print(B > 50)

[[False False  True  True  True]
 [False  True  True  True  True]
 [ True  True False  True  True]
 [ True False False  True  True]
 [ True False  True  True  True]
 [False  True  True  True  True]
 [False False  True False False]
 [False  True False False  True]
 [ True False False  True False]
 [ True  True False  True  True]
 [ True False False  True  True]
 [ True False  True False False]
 [False False False  True False]
 [False  True False  True  True]
 [ True False False False False]
 [ True False  True  True False]
 [False False False False  True]
 [ True False False False False]
 [ True  True  True  True False]
 [False  True False False  True]]


And show value that array

In [41]:
print(B[B>50])

[100 100 100  75 100 100 100  74  77  54  91  93  91  70  51  80  68  55
  57  57  92  74  77  63  86  86  95  90  64  84  81  74  66  76  93  58
  76  61  67  85  82  74  58  65  51  61  53  84  62  98  91  88]


Also, we can use several conditions to find our result.

In [43]:
print(B[(B>50) & (B<80)])

[75 74 77 54 70 51 68 55 57 57 74 77 63 64 74 66 76 58 76 61 67 74 58 65
 51 61 53 62]
