# HOW TO USE NUMPY?
## Part - 1

For the use **Numpy**, in first, import that library.

In [1]:
import numpy as np

Create a **Array** with Numpy with alias **np**

In [2]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


Also, for create a range array with Numpy as follow:

For example, we want to create a range array to 10 than,

``` np.arange(10) ```

as result,

``` [0 1 2 3 4 5 6 7 8 9] ```

In [3]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


Now, we can create a range array **Between** 10 and 30

In [ ]:
x = np.arange(10,30)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


Or, We can define a **Step** for this range

In [5]:
x = np.arange(10,30,2)
print(x)

[10 12 14 16 18 20 22 24 26 28]


Now, we can create a list array with various dimensions

In [6]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


If we want a array with cells of **zero** as follow:

In [11]:
x = np.zeros([5,5])
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


If we want a array with cells **one** as follow:

In [13]:
x = np.ones([2,2])
print(x)

[[1. 1.]
 [1. 1.]]


If we want a array with cells of **custom number** as follow:

In [15]:
x = np.full((4,5),3)
print(x)

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]
