# HOW TO USE NUMPY?
## Part - 5

In [1]:
import numpy as np

In [2]:
ar = np.random.randint(1,100,(5,5))
print(ar)

[[43 15  4 70 24]
 [20 30 29 15 91]
 [14 50 69 34 91]
 [50 29 38 90 96]
 [87 82 69 52 79]]


Operation **statistics** in **Array**

**Mean** in array:

In [3]:
print(np.mean(ar))

50.84


In [4]:
print(np.mean(ar, axis=0))

[42.8 41.2 41.8 52.2 76.2]


In [5]:
print(np.mean(ar,axis=1))

[31.2 37.  51.6 60.6 73.8]


**median** in array:

In [6]:
print(np.median(ar))

50.0


In [7]:
print(np.median(ar, axis=0))

[43. 30. 38. 52. 91.]


In [8]:
print(np.median(ar, axis=1))

[24. 29. 50. 50. 79.]


**Variants** in array:

In [9]:
print(np.var(ar))

823.5744


In [10]:
print(np.var(ar, axis=0))

[670.96 540.56 617.36 692.16 712.56]


In [11]:
print(np.var(ar, axis=1))

[539.76 760.4  716.24 747.84 153.36]


**Standard deviation** in array:

In [12]:
print(np.std(ar,axis=0))

[25.90289559 23.24994624 24.84673017 26.30893384 26.69381951]


In [13]:
print(np.std(ar,axis=1))

[23.23273553 27.57535131 26.76266056 27.34666342 12.38386046]


To find a **maximum** or **minimum** in array:

In [14]:
print(np.max(ar))

96


In [15]:
print(np.max(ar,axis=0))

[87 82 69 90 96]


In [16]:
print(np.max(ar,axis=1))

[70 91 91 96 87]


In [17]:
print(np.min(ar))

4


In [18]:
print(np.min(ar,axis=0))

[14 15  4 15 24]


In [19]:
print(np.min(ar,axis=1))

[ 4 15 14 29 52]


To find argument of **maximum** and **minimum** in array

In [ ]:
print(np.argmax(ar))

19


In [22]:
print(np.argmin(ar))

2


To find **dimension** of array

In [24]:
print(np.shape(ar))

(5, 5)


To **reshape** in array

In [26]:
ar2 = np.linspace(0,100,30)
print(ar2)

[  0.           3.44827586   6.89655172  10.34482759  13.79310345
  17.24137931  20.68965517  24.13793103  27.5862069   31.03448276
  34.48275862  37.93103448  41.37931034  44.82758621  48.27586207
  51.72413793  55.17241379  58.62068966  62.06896552  65.51724138
  68.96551724  72.4137931   75.86206897  79.31034483  82.75862069
  86.20689655  89.65517241  93.10344828  96.55172414 100.        ]


In [30]:
print(np.reshape(ar2,(30,1)))

[[  0.        ]
 [  3.44827586]
 [  6.89655172]
 [ 10.34482759]
 [ 13.79310345]
 [ 17.24137931]
 [ 20.68965517]
 [ 24.13793103]
 [ 27.5862069 ]
 [ 31.03448276]
 [ 34.48275862]
 [ 37.93103448]
 [ 41.37931034]
 [ 44.82758621]
 [ 48.27586207]
 [ 51.72413793]
 [ 55.17241379]
 [ 58.62068966]
 [ 62.06896552]
 [ 65.51724138]
 [ 68.96551724]
 [ 72.4137931 ]
 [ 75.86206897]
 [ 79.31034483]
 [ 82.75862069]
 [ 86.20689655]
 [ 89.65517241]
 [ 93.10344828]
 [ 96.55172414]
 [100.        ]]


In [29]:
print(np.reshape(ar2,(5,6)))

[[  0.           3.44827586   6.89655172  10.34482759  13.79310345
   17.24137931]
 [ 20.68965517  24.13793103  27.5862069   31.03448276  34.48275862
   37.93103448]
 [ 41.37931034  44.82758621  48.27586207  51.72413793  55.17241379
   58.62068966]
 [ 62.06896552  65.51724138  68.96551724  72.4137931   75.86206897
   79.31034483]
 [ 82.75862069  86.20689655  89.65517241  93.10344828  96.55172414
  100.        ]]
