# HOW TO USE NUMPY?
## Part - 3

In [1]:
import numpy as np

In [4]:
np1 = np.array([[1,2],[3,4]])
np2 = np.array([[5,6],[7,8]])

**Note**: Performing mathematical operations on arrays (matrices) requires that they be the same dimensions.

**SUM** operation arrays and numbers.

**array** + **array**:

In [5]:
print(np1+np2)

[[ 6  8]
 [10 12]]


**array** + **number**:

In [6]:
print(np1+5)

[[6 7]
 [8 9]]


SUM with **FUNCTION**

In [10]:
print(np.add(np1,np2))

[[ 6  8]
 [10 12]]


**MINUS** operation arrays and numbers

**array** - **array**:

In [7]:
print(np1 - np2)

[[-4 -4]
 [-4 -4]]


**array** - **number**:

In [8]:
print(np1 - 5)

[[-4 -3]
 [-2 -1]]


MINUS with **FUNCTION**

In [11]:
print(np.subtract(np1,np2))

[[-4 -4]
 [-4 -4]]


**MULTIPLE** operation arrays and number

- **Matrix Multiple**

In [12]:
print(np1@np2)

[[19 22]
 [43 50]]


- **Cells Multiple**

In [13]:
print(np1*np2)

[[ 5 12]
 [21 32]]


In [14]:
print(np1 * 5)

[[ 5 10]
 [15 20]]


**DIVIDE** operation arrays and number

In [ ]:
print(np1 / np2) # With the point number

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
print(np2 // np1) # Without the point number (Just Integer part)

[[5 3]
 [2 2]]
